---
title: "The Study of the Factors Inluencing the Risk of Diagnosed with Coronary Heart Disease(CHD)"
author: "Qing Wen"
date: "2020/12/4"
output: pdf_document
bibliography: reference.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Note(Github Repo)

# Abstract
## Key Words



# Introduction
There has been a rising awareness globally towards improving human health and promoting the importance of tracking one's own health status. As an increasing amount of innovating technology comes out around the world, enhancement in medical equipments and new breakthoughs within the medical field has provided strengthened understanding towards diseases that were once thought untreatable. Doctors and scientists are also utilizing their expertise to convince people what should be done in their normal life as an early prevention for any preventable diseases. 

Among all the diseases that could cause early death of an individual, cardio vascular disease(CVD) accounts for the number one reason of such deaths. According to the [@citeWHO], an estimated 17.9 million people died from CVDs in 2016, which accounted for approximately 31% of the global deaths. Looking more closely, CVD is a group of disorders of the heart and blood vessels, including disorders like cerebrovascular disease, coronary heart disease(CHD), and congenital heart disease. However, even  the high death rate, CVD is considered to be preventable if individuals could address their behavioral risk factors.

With no special preference, CHD is picked as the objective of our study and we want to find potential factors that help determine the risk of individuals being diagnolized with CHD. According to the [@citeMayo], CHD is the disorder caused by the damage to the major blood vessel. Cholesterol-containing deposits accumulate within the arteries and gradually narrow the blood vessels, making it hard to deliver blood and essential nutrients to the heart. As the risk of blocking the blood vessels likely to develop over decades, it becomes difficult for one to early diagnose a problem, probably not  until one got a completely block of the arteries which causes a heart attack.

Therefore, in this study, potential risk factors contributing to the development of CHD is analyzed, and a logistic model is fitted to predict the probability of one being diagnosed with CHD in the future. In the end, we want to develop the importance of paying attention to ceratain health indications to help people adapt a healthier lifestyle in the effort of decreasing the risk of having a CHD. 

The study will be conducted using the data obtained from a well-known longitudinal study regarding heart disease, namely the Framingham Heart Study which was launched in 1948. In the Methodology section, more detailed information on the data would be provided and the underlying theory for the logistic model will be presented. Results regarding the analysis of the variables and the model output will be included in the Result section. Finally, further inferences regarding the results and any weaknesses associated with the study will be included in the Discussion section. 


# Methodology
## Data

## Model



# Result



# Discussion
## Weaknesses

## Next Steps


# References



# Appendix

